/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author matia
 */
import javax.swing.JOptionPane;

public class Ejercicio2 extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Ejercicio2.class.getName());

    /**
     * Creates new form Ejercicio2
     */
    public Ejercicio2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgrMedia = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        lblTemp = new javax.swing.JLabel();
        txtbox = new javax.swing.JTextField();
        rbtnFahrenheit = new javax.swing.JRadioButton();
        rbtnKelvin = new javax.swing.JRadioButton();
        rbtnCelsius = new javax.swing.JRadioButton();
        lblTitulo = new javax.swing.JLabel();
        btnConvertir = new javax.swing.JButton();
        rbtnRadianes = new javax.swing.JRadioButton();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTemp.setText("Ingrese Temperatura en Grados");

        txtbox.addActionListener(this::txtboxActionPerformed);

        bgrMedia.add(rbtnFahrenheit);
        rbtnFahrenheit.setText("A Fahrenheit");
        rbtnFahrenheit.addActionListener(this::rbtnFahrenheitActionPerformed);

        bgrMedia.add(rbtnKelvin);
        rbtnKelvin.setText("A kelvin");

        bgrMedia.add(rbtnCelsius);
        rbtnCelsius.setSelected(true);
        rbtnCelsius.setText("A Celsius");

        lblTitulo.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        lblTitulo.setText("Conversor  de Temperatura");
        lblTitulo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(204, 204, 204), null, null));

        btnConvertir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/refresh icon.png"))); // NOI18N
        btnConvertir.setText("Convertir");
        btnConvertir.setToolTipText("");
        btnConvertir.addActionListener(this::btnConvertirActionPerformed);

        bgrMedia.add(rbtnRadianes);
        rbtnRadianes.setText("A Radianes");
        rbtnRadianes.addActionListener(this::rbtnRadianesActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblTitulo))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(rbtnFahrenheit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rbtnCelsius)
                        .addGap(39, 39, 39))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(rbtnKelvin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rbtnRadianes, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(38, 38, 38))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(txtbox, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(lblTemp))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(btnConvertir, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTemp)
                .addGap(18, 18, 18)
                .addComponent(txtbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtnCelsius)
                    .addComponent(rbtnFahrenheit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtnRadianes)
                    .addComponent(rbtnKelvin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnConvertir, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1))
        );

        rbtnRadianes.getAccessibleContext().setAccessibleParent(jPanel1);

        jDesktopPane1.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(443, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 313, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 81, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbtnRadianesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnRadianesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnRadianesActionPerformed

    private void rbtnFahrenheitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnFahrenheitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnFahrenheitActionPerformed

    private void btnConvertirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConvertirActionPerformed
         //control de errores para que el usuario ingrese solamente numeros
         try {
             //variable que ingresa el usuario y variable del resultado obtenido
        double temperatura;
        double resultado;
         // txtbox.getText() obtiene el texto que escribió el usuario.
        // Double.parseDouble() convierte ese texto de String a un número decimal (double).
        temperatura = Double.parseDouble(txtbox.getText());
        
          // Verificamos si el RadioButton "A Fahrenheit"
         // está seleccionado.

        if (rbtnFahrenheit.isSelected()) {
             // Aplicamos la fórmula para convertir Celsius a Fahrenheit:
            // Fahrenheit = Celsius × 9/5 + 32
            resultado = temperatura * 9 / 5 + 32;
            
            // Mostramos el resultado en una ventana emergente.
            JOptionPane.showMessageDialog(
                    
//             "this" indica que la ventana emergente
//            pertenece a nuestro JFrame actual.
//            Texto que aparecerá en la ventana.
//           String.format("%.2f", resultado) hace que
//           el resultado tenga solamente 2 decimales.
                    this,
                    "La temperatura en grados Fahrenheit es: "
                    + String.format("%.2f", resultado) + " °F"
            );
//         Si Fahrenheit no está seleccionado,
//         verificamos si está seleccionado Celsius.
        } else if (rbtnCelsius.isSelected()) {

            resultado = temperatura;

            JOptionPane.showMessageDialog(
                    this,
                    "La temperatura en grados Celsius es: "
                    + String.format("%.2f", resultado) + " °C"
            );
            } else if (rbtnRadianes.isSelected()) {

            resultado = Math.toRadians(temperatura);

            JOptionPane.showMessageDialog(
                    this,
                    "El valor en radianes es: "
                    + String.format("%.2f", resultado) + " rad"
            );

        } else {
//             Avisamos al usuario que debe seleccionar
//             una unidad de conversión.
            JOptionPane.showMessageDialog(
                    this,
                    "Debe seleccionar una unidad."
            );
        }
//       Si el usuario escribe algo que no se puede convertir
//       a un número, por ejemplo "hola", se produce
//       un error llamado NumberFormatException.
    } catch (NumberFormatException e) {
// mostramos el msj al usuario
        JOptionPane.showMessageDialog(
                this,
                "Debe ingresar un número válido."
        );
    }
    }//GEN-LAST:event_btnConvertirActionPerformed

    private void txtboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtboxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Ejercicio2().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgrMedia;
    private javax.swing.JButton btnConvertir;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblTemp;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JRadioButton rbtnCelsius;
    private javax.swing.JRadioButton rbtnFahrenheit;
    private javax.swing.JRadioButton rbtnKelvin;
    private javax.swing.JRadioButton rbtnRadianes;
    private javax.swing.JTextField txtbox;
    // End of variables declaration//GEN-END:variables
}
